### ISSUE TITLE
Consider versioning and location of MetCoOp CAP profile specification

### ISSUE THREAD

**Issue by petringo** [fmidev/metcoop-wg-backend#6]
Following questions would need to be answered.

1. What is the permanent (base) url to the profile specification?
2. How to determine which version is newer or older or same than other?
3. How to determine (backwards) compatible versions (for end user)?
4. How to determine it is a MetCoOp CAP profile, when version is previously unknown to the end user?
    * e.g. when inspecting \<code> element of a CAP document

**Comment by tervo** [comment]
We shall use github document. Versioning can be achieved with releases. 
We shall create metcoop organisation and move this repository to there.

**Comment by tervo** [comment]
We will get a public repo from SMHI GitLab where other MetCoOp repos are located as well. I will move this content to the new repo once it created.

**Comment by petringo** [comment]
To have meaningful releases, I would suggest that the CAP profile repository (with meeting notes etc, as discussed in [last meeting](https://github.com/fmidev/metcoop-wg-backend/blob/master/meetings/remote_meeting_2020_02.md)) should be separated from other activities (e.g. time series etc.) of the MetCoOp WG Backend.

**Comment by tervo** [comment]
The specification is now in https://git.smhi.se/metcoop/metcoop-cap-profile/blob/version-1.0/metcoop-cap-profile.md. [The old version](https://github.com/fmidev/metcoop-wg-backend/blob/master/metcoop-cap-profile.md) is updated corresponding. 

Versioning can be handled with tags. Currently, there is a tag for version 1.0: https://git.smhi.se/metcoop/metcoop-cap-profile/blob/version-1.0/metcoop-cap-profile.md

Unfortunately, issues didn't move because the repository wasn't imported from GitHub properly. New issues should be made to the new repository. 

The new repository is only for MetCoOp CAP profile. A location of other work shall be discussed in the future.
